name: Android Build
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install
      #    haxelib remove SScript
       #   haxelib remove hxCodec
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set hxCodec 2.6.1
          haxelib set flixel 5.5.0
          haxelib set openfl 9.2.2
          haxelib set lime 8.0.2
          haxelib set SScript 8.1.6
          haxelib set flixel-addons 3.0.2
          haxelib set hxcpp 4.2.1
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa
      - name: Building
        run: |
         haxelib run lime build android -D DISABLED_MACRO_SUPERLATIVE -D NO_PRECOMPILED_HEADERS -D officialBuild -final

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: RingsOfHell-Mobile
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
